### ISSUE TITLE
Remove references to retake - the previous project name.

### ISSUE THREAD

**Issue by data-envoy** [paradedb/helm-charts#32]
**To Reproduce**

https://github.com/search?q=repo%3Aparadedb%2Fhelm-charts%20retake&type=code

**Comment by philippemnoel** [comment]
Thank you for flagging, we will fix this ASAP! @MauAraujo

**Comment by MauAraujo** [comment]
Fixed in https://github.com/paradedb/helm-charts/commit/2c3bb89c72512ae53794d850fb7a77a1d9832091
