### ISSUE TITLE
Possible mistake in readme - Postgres as a prerequisite

### ISSUE THREAD

**Issue by data-envoy** [paradedb/helm-charts#33]
**Describe the bug**

I think the following is a mistake, if I understand correctly then the Postgres instances are deployed in [templates/postgres.yaml](https://github.com/paradedb/helm-charts/blob/main/charts/paradedb/templates/postgres.yaml), so they aren't a prerequisite.

> [Prerequisites](https://github.com/paradedb/helm-charts/tree/main#prerequisites)
> A Postgres database that can be accessed from the cluster

BTW this looks very cool, I look forward to trialing it when I have time in a few weeks :)

**Comment by MauAraujo** [comment]
Thanks! That was a reference to the old product too, I removed it. And yes, it would be cool if you tried ParadeDB :smiley:
